#ifndef __show_my_frame__
#define __show_my_frame__

/**
@file
Subclass of MyFrame, which is generated by wxFormBuilder.
*/

#include "wx_hash_gui.h"

//// end generated include

/** Implementing MyFrame */
class ShowMyFrame : public MyFrame
{
protected:
    // Handlers for MyFrame events.
    void CalculateHash(wxCommandEvent& event);
    void Clear(wxCommandEvent& event);
    void Quit(wxCommandEvent& event);
public:
    /** Constructor */
    ShowMyFrame(wxWindow* parent);
    //// end generated class members

};

#endif // __show_my_frame__
